version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ExchangeRateUpdater.API/Dockerfile
    environment:
      - BankApis__CzechBank__BaseAddress=https://api.cnb.cz/cnbapi/exrates/daily
      - ConnectionStrings__DefaultConnection=server=db;database=MewsTestDB;user=root;password=MewsTest1234
      - ApiKey=a12345
    ports:
      - "5094:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MewsTest1234
      MYSQL_DATABASE: MewsTestDB
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  

volumes:
  db_data:
